<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IHIJH93" failures="1" tests="5" name="Default test(failed)" time="0.056" errors="0" timestamp="2022-08-14T20:03:00 IST">
  <testcase classname="com.actitime.testscript.TestExecutionWay" name="modifyCustomer" time="0.006"/>
  <testcase classname="com.actitime.testscript.TestExecutionWay" name="createCustomer" time="0.001"/>
  <testcase classname="com.actitime.testscript.TestExecutionWay" name="createCustomer" time="0.001"/>
  <testcase classname="com.actitime.testscript.TestExecutionWay" name="createCustomer" time="0.001"/>
  <testcase classname="com.actitime.testscript.TestExecutionWay" name="deleteCustomer" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.actitime.testscript.TestExecutionWay.deleteCustomer(TestExecutionWay.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
</testsuite> <!-- Default test(failed) -->
